"""Add SearchBatch model

Revision ID: 68b945c02a08
Revises: 1ffa5496b530
Create Date: 2026-06-05 12:48:43.038863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b945c02a08'
down_revision: Union[str, Sequence[str], None] = '1ffa5496b530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lead_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_batches_id'), 'search_batches', ['id'], unique=False)
    op.add_column('leads', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'search_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'batch_id')
    op.drop_index(op.f('ix_search_batches_id'), table_name='search_batches')
    op.drop_table('search_batches')
    # ### end Alembic commands ###
